// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP9hvQn1dPrglI3TnFyefHSwluYiK8wuI',
    appId: '1:292739207726:web:c801d538566aaec36c85bf',
    messagingSenderId: '292739207726',
    projectId: 'e-commerce-85d92',
    authDomain: 'e-commerce-85d92.firebaseapp.com',
    storageBucket: 'e-commerce-85d92.firebasestorage.app',
    measurementId: 'G-D8RJC69J7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAej6qbxuKQWQt5sV3bCJWmVwVlul_VboE',
    appId: '1:292739207726:android:5eb9b1c3774107bc6c85bf',
    messagingSenderId: '292739207726',
    projectId: 'e-commerce-85d92',
    storageBucket: 'e-commerce-85d92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOM2vBKBq_1JJb2e6l9p-sSmD5SB9tSlI',
    appId: '1:292739207726:ios:b6568a33fbf425b16c85bf',
    messagingSenderId: '292739207726',
    projectId: 'e-commerce-85d92',
    storageBucket: 'e-commerce-85d92.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOM2vBKBq_1JJb2e6l9p-sSmD5SB9tSlI',
    appId: '1:292739207726:ios:b6568a33fbf425b16c85bf',
    messagingSenderId: '292739207726',
    projectId: 'e-commerce-85d92',
    storageBucket: 'e-commerce-85d92.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP9hvQn1dPrglI3TnFyefHSwluYiK8wuI',
    appId: '1:292739207726:web:85928af95cdd4b9b6c85bf',
    messagingSenderId: '292739207726',
    projectId: 'e-commerce-85d92',
    authDomain: 'e-commerce-85d92.firebaseapp.com',
    storageBucket: 'e-commerce-85d92.firebasestorage.app',
    measurementId: 'G-YBDLJV2RMR',
  );
}
